### ISSUE TITLE
手机连接此蓝牙键盘要求输入Pin的问题可否解决呢

### ISSUE THREAD

**Issue by genokolar** [Lotlab/Lot60-BLE-Keyboard#1]
手机连接此蓝牙键盘要求输入Pin的问题可否解决呢？不是很了解有的蓝牙

**Comment by jim-kirisame** [comment]
软件的问题到隔壁 lotlab/nrf51822-keyboard 去问啦

这个其实是一个特性，可以将[这一行](https://github.com/Lotlab/nrf51822-keyboard/blob/9ccda83f3b5e3f801f2263920ba39658091f481b/main/ble/ble_services.c#L77)修改为 BLE_GAP_IO_CAPS_NONE。具体的原理可以参考http://blog.chinaunix.net/uid-28852942-id-5753120.html 和 https://blog.csdn.net/zwj695535100/article/details/50785731

**Comment by genokolar** [comment]
嗯嗯。刚在学习怎么设置为不要配对码模式。谢谢。
