### ISSUE TITLE
'sdld.exe' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by lxj5891** [Lotlab/Lot60-BLE-Keyboard#10]
'sdld.exe' 不是内部或外部命令，也不是可运行的程序

**Comment by lxj5891** [comment]
make[1]: 进入目录“/d/code/nrf52-keyboard/keyboard/lot60-ble/rev_c”
DONE nrf52_kbd
Packing: ../_build/rev_c/nrf52_kbd.hex
nrfutil pkg generate --hw-version 52 --application-version 1 --application ../_build/rev_c/nrf52_kbd.hex \
--sd-req 0xb8 --key-file ../common/../../../application/main/project/private.key ../_build/lot60-ble-rev_c-nrf52-2022_02_06-v1.1.6.0-1-gb5565be-dirty.zip
Zip created at ../_build/lot60-ble-rev_c-nrf52-2022_02_06-v1.1.6.0-1-gb5565be-dirty.zip
Linking target: ch554.ihx
'sdld.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
make[1]: *** [../common/../../../usb/usb.mk:64：../_build/rev_c/ch554/ch554.ihx] 错误 1
make[1]: 离开目录“/d/code/nrf52-keyboard/keyboard/lot60-ble/rev_c”
make: *** [Makefile:29：rev_c] 错误 2

**Comment by jim-kirisame** [comment]
检查你的sdcc
