### ISSUE TITLE
Arrow key compatibility / 64 keys

### ISSUE THREAD

**Issue by SinanAkkoyun** [Lotlab/Lot60-BLE-Keyboard#6]
Hello,
thank you for the great work!

Is this PCB 64 key compatible? I mean with arrow keys?

Thank you very much!

**Comment by SinanAkkoyun** [comment]
I just found out that this board does not support 64 key arrow keys, I think...

Are there any alternatives with the same chip and same everything just with arrow keys?

**Comment by jim-kirisame** [comment]
Hi, this project is a "reference design" of the [firmware](https://github.com/Lotlab/nrf52-keyboard). If there is any missing feature, you could add it by yourself.

**Comment by SinanAkkoyun** [comment]
Hi, I want to add the 64 key layout.
I do not quite understand where to get the exact measurements and how to wire the switches up there...

Could you please help me in some way or lead me to a reference design for a 64 key PCB? I searched for weeks and did not find anything...

Would it even be possible?

Thank you so much!
