### ISSUE TITLE
PCB thickness

### ISSUE THREAD

**Issue by SinanAkkoyun** [Lotlab/Lot60-BLE-Keyboard#7]
Hello, which PCB thickness is recommended?

**Comment by jim-kirisame** [comment]
1.6mm is recommend

**Comment by TaliTheBag** [comment]
can I use both battery socket at the same time?

**Comment by jim-kirisame** [comment]
@TaliTheBag no.

**Comment by TaliTheBag** [comment]
so what's is the purpose for the second battery slot? just for rerouting?
