### ISSUE TITLE
Rev.GX and Rev.GHS released - will Rev.G be open source?

### ISSUE THREAD

**Issue by pseudobacon** [Lotlab/Lot60-BLE-Keyboard#8]
As per the title, now that Rev.GHS has been released will Rev.G be released open source?

**Comment by jim-kirisame** [comment]
Rev.GX contains some minor footprint change compare to Rev.G, that's why we call it GX instead of H. GX is still G, so we will open source G/GX when GX is not selling anymore.

By the way, why you want to get the hardware for Rev.G? I think Rev.F is enough as a reference keyboard design.

**Comment by pseudobacon** [comment]
Oh I see. G has the onboard debugger, makes it a lot easier to program the nordic chip without additional tools

**Comment by jim-kirisame** [comment]
It's not hard for you to add onboard debugger, just connect P1.0 to swdio and P1.1 to swdclk directly, then enable it in the firmware config.
